Piece [] make(int[][] quadro) {
  Piece[] p = new Piece[10];
  switch(versao) {
  default:
  case 1:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(1, 0, 2, quadro);
    p[4] = new Piece(1, 3, 2, quadro);
    p[5] = new Piece(2, 1, 2, quadro);
    p[6] = new Piece(3, 1, 3, quadro);
    p[7] = new Piece(3, 2, 3, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 2:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(1, 0, 3, quadro);
    p[4] = new Piece(1, 3, 3, quadro);
    p[5] = new Piece(2, 1, 2, quadro);
    p[6] = new Piece(3, 0, 2, quadro);
    p[7] = new Piece(3, 3, 2, quadro);
    p[8] = new Piece(3, 1, 3, quadro);
    p[9] = new Piece(3, 2, 3, quadro);
    break;
  case 3:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 1, quadro);
    p[2] = new Piece(1, 3, 1, quadro);
    p[3] = new Piece(1, 1, 2, quadro);
    p[4] = new Piece(1, 2, 2, quadro);
    p[5] = new Piece(2, 0, 4, quadro);
    p[6] = new Piece(3, 0, 3, quadro);
    p[7] = new Piece(3, 3, 3, quadro);
    p[8] = new Piece(3, 2, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 4:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(1, 0, 3, quadro);
    p[4] = new Piece(1, 3, 3, quadro);
    p[5] = new Piece(2, 1, 3, quadro);
    p[6] = new Piece(3, 0, 2, quadro);
    p[7] = new Piece(3, 1, 2, quadro);
    p[8] = new Piece(3, 2, 2, quadro);
    p[9] = new Piece(3, 3, 2, quadro);
    break;
  case 5:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 1, quadro);
    p[2] = new Piece(1, 3, 1, quadro);
    p[3] = new Piece(1, 0, 3, quadro);
    p[4] = new Piece(1, 3, 3, quadro);
    p[5] = new Piece(2, 1, 2, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 1, 3, quadro);
    p[9] = new Piece(3, 2, 3, quadro);
    break;
  case 6:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 0, 2, quadro);
    p[3] = new Piece(1, 3, 2, quadro);
    p[4] = new Piece(1, 1, 3, quadro);
    p[5] = new Piece(2, 1, 2, quadro);
    p[6] = new Piece(3, 3, 0, quadro);
    p[7] = new Piece(3, 3, 1, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 7:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 2, quadro);
    p[2] = new Piece(1, 1, 2, quadro);
    p[3] = new Piece(1, 2, 2, quadro);
    p[4] = new Piece(1, 3, 2, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 0, 1, quadro);
    p[9] = new Piece(3, 3, 1, quadro);
    break;
  case 8:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 1, quadro);
    p[2] = new Piece(1, 3, 1, quadro);
    p[3] = new Piece(1, 1, 2, quadro);
    p[4] = new Piece(1, 2, 2, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 0, 3, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 9:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 0, 2, quadro);
    p[3] = new Piece(1, 1, 2, quadro);
    p[4] = new Piece(1, 2, 2, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 3, 0, quadro);
    p[7] = new Piece(3, 3, 1, quadro);
    p[8] = new Piece(3, 3, 2, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 10:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 0, 2, quadro);
    p[3] = new Piece(1, 3, 2, quadro);
    p[4] = new Piece(1, 2, 3, quadro);
    p[5] = new Piece(2, 1, 2, quadro);
    p[6] = new Piece(3, 3, 0, quadro);
    p[7] = new Piece(3, 3, 1, quadro);
    p[8] = new Piece(3, 1, 3, quadro);
    p[9] = new Piece(3, 1, 4, quadro);
    break;
  case 11:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 0, 2, quadro);
    p[3] = new Piece(1, 1, 3, quadro);
    p[4] = new Piece(1, 2, 3, quadro);
    p[5] = new Piece(2, 1, 2, quadro);
    p[6] = new Piece(3, 3, 0, quadro);
    p[7] = new Piece(3, 3, 1, quadro);
    p[8] = new Piece(3, 3, 2, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 12:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 3, quadro);
    p[2] = new Piece(1, 1, 3, quadro);
    p[3] = new Piece(1, 2, 3, quadro);
    p[4] = new Piece(1, 3, 3, quadro);
    p[5] = new Piece(2, 1, 2, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 0, 1, quadro);
    p[9] = new Piece(3, 3, 1, quadro);
    break;
  case 13:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 0, 3, quadro);
    p[3] = new Piece(1, 3, 3, quadro);
    p[4] = new Piece(2, 0, 2, quadro);
    p[5] = new Piece(2, 1, 3, quadro);
    p[6] = new Piece(3, 3, 0, quadro);
    p[7] = new Piece(3, 3, 1, quadro);
    p[8] = new Piece(3, 2, 2, quadro);
    p[9] = new Piece(3, 3, 2, quadro);
    break;
  case 14:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(1, 1, 2, quadro);
    p[4] = new Piece(2, 0, 4, quadro);
    p[5] = new Piece(2, 2, 4, quadro);
    p[6] = new Piece(3, 0, 2, quadro);
    p[7] = new Piece(3, 3, 2, quadro);
    p[8] = new Piece(3, 0, 3, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 15:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 1, quadro);
    p[2] = new Piece(1, 3, 1, quadro);
    p[3] = new Piece(1, 1, 2, quadro);
    p[4] = new Piece(2, 0, 4, quadro);
    p[5] = new Piece(2, 2, 4, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 0, 3, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 16:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 0, 2, quadro);
    p[3] = new Piece(1, 3, 2, quadro);
    p[4] = new Piece(2, 1, 2, quadro);
    p[5] = new Piece(2, 1, 3, quadro);
    p[6] = new Piece(3, 3, 0, quadro);
    p[7] = new Piece(3, 3, 1, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 17:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(1, 1, 3, quadro);
    p[4] = new Piece(2, 0, 2, quadro);
    p[5] = new Piece(2, 2, 2, quadro);
    p[6] = new Piece(3, 0, 3, quadro);
    p[7] = new Piece(3, 3, 3, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 18:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(2, 1, 2, quadro);
    p[4] = new Piece(2, 1, 3, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 0, 2, quadro);
    p[7] = new Piece(3, 3, 2, quadro);
    p[8] = new Piece(3, 0, 3, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 19:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 1, quadro);
    p[2] = new Piece(1, 3, 1, quadro);
    p[3] = new Piece(2, 1, 2, quadro);
    p[4] = new Piece(2, 1, 3, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 0, 3, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 20:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 3, 0, quadro);
    p[2] = new Piece(1, 0, 2, quadro);
    p[3] = new Piece(2, 1, 2, quadro);
    p[4] = new Piece(2, 1, 3, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 0, 1, quadro);
    p[8] = new Piece(3, 3, 2, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 21:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 2, quadro);
    p[2] = new Piece(1, 1, 2, quadro);
    p[3] = new Piece(2, 2, 2, quadro);
    p[4] = new Piece(2, 2, 3, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 0, 1, quadro);
    p[9] = new Piece(3, 3, 1, quadro);
    break;
  case 22:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(2, 0, 2, quadro);
    p[4] = new Piece(2, 2, 2, quadro);
    p[5] = new Piece(2, 1, 3, quadro);
    p[6] = new Piece(3, 0, 3, quadro);
    p[7] = new Piece(3, 3, 3, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 23:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(2, 1, 2, quadro);
    p[4] = new Piece(2, 0, 3, quadro);
    p[5] = new Piece(2, 2, 3, quadro);
    p[6] = new Piece(3, 0, 2, quadro);
    p[7] = new Piece(3, 3, 2, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 24:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(2, 0, 2, quadro);
    p[3] = new Piece(2, 2, 2, quadro);
    p[4] = new Piece(2, 0, 3, quadro);
    p[5] = new Piece(2, 2, 3, quadro);
    p[6] = new Piece(3, 3, 0, quadro);
    p[7] = new Piece(3, 3, 1, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 25:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 2, quadro);
    p[2] = new Piece(2, 2, 2, quadro);
    p[3] = new Piece(2, 2, 3, quadro);
    p[4] = new Piece(2, 0, 4, quadro);
    p[5] = new Piece(2, 2, 4, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 0, 1, quadro);
    p[9] = new Piece(3, 3, 1, quadro);
    break;
  case 26:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(2, 1, 2, quadro);
    p[3] = new Piece(2, 0, 3, quadro);
    p[4] = new Piece(2, 2, 3, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 3, 0, quadro);
    p[7] = new Piece(3, 3, 1, quadro);
    p[8] = new Piece(3, 0, 2, quadro);
    p[9] = new Piece(3, 3, 2, quadro);
    break;
  case 27:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(2, 0, 2, quadro);
    p[2] = new Piece(2, 2, 2, quadro);
    p[3] = new Piece(2, 0, 3, quadro);
    p[4] = new Piece(2, 2, 3, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 0, 1, quadro);
    p[9] = new Piece(3, 3, 1, quadro);
    break;
  case 28:
    p[0] = new Piece(4, 1, 1, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(1, 3, 2, quadro);
    p[4] = new Piece(1, 0, 3, quadro);
    p[5] = new Piece(2, 1, 3, quadro);
    p[6] = new Piece(3, 1, 0, quadro);
    p[7] = new Piece(3, 2, 0, quadro);
    p[8] = new Piece(3, 0, 2, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 29:
    p[0] = new Piece(4, 2, 0, quadro);
    p[1] = new Piece(2, 0, 1, quadro);
    p[2] = new Piece(2, 0, 2, quadro);
    p[3] = new Piece(2, 2, 2, quadro);
    p[4] = new Piece(2, 0, 3, quadro);
    p[5] = new Piece(2, 2, 3, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 1, 0, quadro);
    p[8] = new Piece(3, 2, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 30:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 2, quadro);
    p[2] = new Piece(1, 3, 2, quadro);
    p[3] = new Piece(1, 1, 3, quadro);
    p[4] = new Piece(1, 2, 3, quadro);
    p[5] = new Piece(2, 1, 2, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 3, 0, quadro);
    p[8] = new Piece(3, 0, 1, quadro);
    p[9] = new Piece(3, 3, 1, quadro);
    break;
  case 31:
    p[0] = new Piece(4, 1, 1, quadro);
    p[1] = new Piece(1, 0, 1, quadro);
    p[2] = new Piece(1, 3, 1, quadro);
    p[3] = new Piece(2, 0, 0, quadro);
    p[4] = new Piece(2, 2, 0, quadro);
    p[5] = new Piece(2, 1, 3, quadro);
    p[6] = new Piece(3, 0, 3, quadro);
    p[7] = new Piece(3, 3, 3, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 32:
    p[0] = new Piece(4, 0, 0, quadro);
    p[1] = new Piece(1, 2, 1, quadro);
    p[2] = new Piece(1, 0, 2, quadro);
    p[3] = new Piece(1, 1, 2, quadro);
    p[4] = new Piece(2, 2, 0, quadro);
    p[5] = new Piece(2, 1, 4, quadro);
    p[6] = new Piece(3, 3, 1, quadro);
    p[7] = new Piece(3, 3, 2, quadro);
    p[8] = new Piece(3, 2, 3, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 33:
    p[0] = new Piece(4, 2, 3, quadro);
    p[1] = new Piece(1, 1, 0, quadro);
    p[2] = new Piece(1, 2, 0, quadro);
    p[3] = new Piece(1, 3, 0, quadro);
    p[4] = new Piece(2, 0, 2, quadro);
    p[5] = new Piece(2, 0, 3, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 0, 1, quadro);
    p[8] = new Piece(3, 2, 2, quadro);
    p[9] = new Piece(3, 3, 2, quadro);
    break;
  case 34:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(1, 0, 2, quadro);
    p[4] = new Piece(1, 1, 2, quadro);
    p[5] = new Piece(1, 3, 2, quadro);
    p[6] = new Piece(3, 2, 2, quadro);
    p[7] = new Piece(3, 2, 3, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 35:
    p[0] = new Piece(4, 1, 0, quadro);
    p[1] = new Piece(1, 0, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(2, 0, 2, quadro);
    p[4] = new Piece(2, 2, 2, quadro);
    p[5] = new Piece(2, 1, 3, quadro);
    p[6] = new Piece(3, 0, 3, quadro);
    p[7] = new Piece(3, 3, 3, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 36:
    p[0] = new Piece(4, 2, 0, quadro);
    p[1] = new Piece(1, 3, 3, quadro);
    p[2] = new Piece(2, 0, 0, quadro);
    p[3] = new Piece(2, 0, 1, quadro);
    p[4] = new Piece(2, 0, 2, quadro);
    p[5] = new Piece(2, 2, 2, quadro);
    p[6] = new Piece(3, 0, 3, quadro);
    p[7] = new Piece(3, 2, 3, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 2, 4, quadro);
    break;
  case 37:
    p[0] = new Piece(4, 0, 0, quadro);
    p[1] = new Piece(1, 3, 0, quadro);
    p[2] = new Piece(2, 0, 2, quadro);
    p[3] = new Piece(2, 2, 2, quadro);
    p[4] = new Piece(2, 0, 3, quadro);
    p[5] = new Piece(2, 2, 3, quadro);
    p[6] = new Piece(3, 2, 0, quadro);
    p[7] = new Piece(3, 2, 1, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 38:
    p[0] = new Piece(4, 0, 0, quadro);
    p[1] = new Piece(1, 2, 0, quadro);
    p[2] = new Piece(1, 3, 0, quadro);
    p[3] = new Piece(1, 0, 3, quadro);
    p[4] = new Piece(1, 1, 3, quadro);
    p[5] = new Piece(2, 0, 2, quadro);
    p[6] = new Piece(3, 2, 2, quadro);
    p[7] = new Piece(3, 3, 2, quadro);
    p[8] = new Piece(3, 2, 3, quadro);
    p[9] = new Piece(3, 3, 3, quadro);
    break;
  case 39:
    p[0] = new Piece(4, 0, 0, quadro);
    p[1] = new Piece(1, 0, 2, quadro);
    p[2] = new Piece(1, 1, 2, quadro);
    p[3] = new Piece(2, 2, 0, quadro);
    p[4] = new Piece(2, 2, 1, quadro);
    p[5] = new Piece(2, 2, 2, quadro);
    p[6] = new Piece(3, 2, 3, quadro);
    p[7] = new Piece(3, 3, 3, quadro);
    p[8] = new Piece(3, 0, 4, quadro);
    p[9] = new Piece(3, 3, 4, quadro);
    break;
  case 40:
    p[0] = new Piece(4, 0, 1, quadro);
    p[1] = new Piece(1, 3, 0, quadro);
    p[2] = new Piece(1, 2, 1, quadro);
    p[3] = new Piece(1, 3, 2, quadro);
    p[4] = new Piece(2, 1, 3, quadro);
    p[5] = new Piece(2, 2, 4, quadro);
    p[6] = new Piece(3, 0, 0, quadro);
    p[7] = new Piece(3, 1, 0, quadro);
    p[8] = new Piece(3, 2, 0, quadro);
    p[9] = new Piece(3, 1, 4, quadro);
    break;
  }
  return p;
}
